### ISSUE TITLE
No module named 'nmf.cylib.nnls_bpp_utils'

### ISSUE THREAD

**Issue by shivanisrivarshini** [lilab-bcb/nmf-torch#7]
../nmf-torch/nmf/utils/_nnls_bpp.py in <module>()
      4 import torch
      5 
      6 from nmf.cylib.nnls_bpp_utils import _nnls_bpp
      7 
      8 def nnls_bpp(CTC, CTB, X, device_type) -> int:

ModuleNotFoundError: No module named 'nmf.cylib.nnls_bpp_utils'

**Comment by bli25** [comment]
@shivanisrivarshini, have you compiled with Cython?

**Comment by yihming** [comment]
Hi @shivanisrivarshini ,

It looks like the Cython code in `nmf-torch/ext_modules` was not compiled successfully. Could you please let us know how you installed `nmf-torch` on your local machine?

If installing from source code, it's recommended using 
```
pip install .
```
command within the repo folder.


Sincerely,
Yiming

**Comment by yihming** [comment]
@shivanisrivarshini I'll close this issue for now. Please feel free to reopen it if the issue still remains.
